import test from 'node:test';
import assert from 'node:assert/strict';
import { buildAuthorizeUrl, createPkcePair, deletePost, exchangeCode, getAuthenticatedUser, listOwnPosts, refreshAccessToken, X_SCOPES } from '../src/connectors/x.js';

function response(status, data, headers={}) { return new Response(JSON.stringify(data), { status, headers:{'content-type':'application/json',...headers} }); }

test('PKCE produces S256-compatible values',()=>{const p=createPkcePair();assert.ok(p.verifier.length>=43);assert.ok(p.challenge.length>=43);assert.notEqual(p.verifier,p.challenge)});
test('authorize URL contains required scopes and PKCE',()=>{const u=new URL(buildAuthorizeUrl({clientId:'cid',redirectUri:'http://127.0.0.1:4177/api/x/callback',state:'state1',challenge:'challenge1'}));assert.equal(u.origin,'https://x.com');assert.equal(u.searchParams.get('code_challenge_method'),'S256');for(const s of X_SCOPES)assert.ok(u.searchParams.get('scope').includes(s))});
test('authorization code exchange posts expected form values',async()=>{let seen;const fetchImpl=async(url,init)=>{seen={url,method:init.method,body:init.body.toString()};return response(200,{access_token:'a',refresh_token:'r',expires_in:7200})};const data=await exchangeCode({clientId:'cid',code:'code',redirectUri:'http://local/cb',verifier:'verify'},{fetchImpl});assert.equal(data.access_token,'a');assert.match(seen.body,/grant_type=authorization_code/);assert.match(seen.body,/code_verifier=verify/)});
test('refresh token flow returns rotated token',async()=>{const fetchImpl=async()=>response(200,{access_token:'new-a',refresh_token:'new-r'});const data=await refreshAccessToken({clientId:'cid',refreshToken:'old-r'},{fetchImpl});assert.equal(data.refresh_token,'new-r')});
test('users/me maps identity',async()=>{const fetchImpl=async()=>response(200,{data:{id:'42',username:'alice',name:'Alice'}});assert.deepEqual(await getAuthenticatedUser('token',{fetchImpl}),{id:'42',username:'alice',name:'Alice',profileImageUrl:undefined})});
test('user posts pagination maps posts',async()=>{let calls=0;const fetchImpl=async()=>{calls++;return calls===1?response(200,{data:[{id:'1',text:'one',created_at:'2026-01-01T00:00:00Z'}],meta:{next_token:'next'}}):response(200,{data:[{id:'2',text:'two',created_at:'2026-01-02T00:00:00Z'}],meta:{}})};const data=await listOwnPosts('token','42',{}, {fetchImpl});assert.equal(data.length,2);assert.equal(calls,2);assert.equal(data[1].url,'https://x.com/i/web/status/2')});
test('delete post uses DELETE and reports success',async()=>{let method;const fetchImpl=async(_url,init)=>{method=init.method;return response(200,{data:{deleted:true}})};assert.deepEqual(await deletePost('token','99',{fetchImpl}),{id:'99',deleted:true});assert.equal(method,'DELETE')});
test('429 exposes reset timestamp',async()=>{const fetchImpl=async()=>response(429,{title:'Too Many Requests'},{'x-rate-limit-reset':'1999999999'});await assert.rejects(()=>getAuthenticatedUser('token',{fetchImpl}),(e)=>e.status===429&&e.rateLimitReset===1999999999)});
